name: gitleaks
on: [pull_request]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set execute permission
        run: chmod +x ./run_gitleaks.sh
      - name: Run Gitleaks scan
        run: |
          ./run_gitleaks.sh "${{ secrets.GITHUB_TOKEN }}"
