name: gitleaks
on: [pull_request]
jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  gitleaks_scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permission
        run: chmod +x ./run_gitleaks.sh

      - name: Run Gitleaks Scan
        run: ./run_gitleaks.sh "${{ secrets.GITHUB_TOKEN }}" "${{ github.event}}"
