name: Gitleaks Scan

on: pull_request

jobs:
  gitleaks_scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set execute permission
      run: chmod +x ./run_gitleaks.sh
      
    - name: Run Gitleaks Scan
      run: ./run_gitleaks.sh "${{ secrets.GITHUB_TOKEN }}" "${{ github.event.pull_request.number }}"